services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    labels:
      - app=watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TIMEZONE}
      WATCHTOWER_SCHEDULE: "0 */5 * * * *"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LOG_FORMAT: JSON
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATIONS_LEVEL: error
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${DOMAIN}
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: dario.mauri9@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: dario.mauri9@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: dario.mauri9@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "${EMAIL_SERVER_PASSWORD}"
    read_only: true