services:
  lab-home:
    image: dariomr8/lab-home:latest
    restart: unless-stopped
    expose:
      - "80"
    networks: [ backend ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 5s
      retries: 3

  api-stress-test:
    image: dariomr8/api-stress-test:latest
    restart: unless-stopped
    expose:
      - "8083"
    networks: [ backend ]
    environment:
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
    labels:
      - app=api-stress-test
      - metrics_scrape=true
      - metrics_path=/actuator/prometheus
      - metrics_port=8083

  ichiro-family-tree:
    image: dariomr8/ichiro:latest
    restart: unless-stopped
    expose:
      - "8081"
    networks: [ backend ]
    environment:
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
    labels:
      - app=ichiro-family-tree
      - metrics_scrape=true
      - metrics_path=/actuator/prometheus
      - metrics_port=8081

  shortly:
    image: dariomr8/shortly:latest
    restart: unless-stopped
    expose:
      - "8082"
    networks: [ backend ]
    environment:
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
    labels:
      - app=shortly
      - metrics_scrape=true
      - metrics_path=/actuator/prometheus
      - metrics_port=8082

  ichiro-walks:
    image: dariomr8/ichiro-walks:latest
    restart: unless-stopped
    expose:
      - "8085"
    networks: [ backend ]
    environment:
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
    labels:
      - app=ichiro-walks
      - metrics_scrape=true
      - metrics_path=/actuator/prometheus
      - metrics_port=8085

  htmx-demo:
    image: dariomr8/htmx-demo:latest
    restart: unless-stopped
    expose:
      - "8087"
    networks: [ backend ]
    labels:
      - app=htmx-demo
      - metrics_scrape=true
      - metrics_path=/actuator/prometheus
      - metrics_port=8087

  wordle-duel-service:
    image: dariomr8/wordle-duel-service:latest
    restart: unless-stopped
    expose:
      - "8088"
    networks: [ backend, wordle_duel_service_internal ]
    depends_on:
      wordle-duel-service-redis:
        condition: service_healthy
    environment:
      TZ: ${TIMEZONE}
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
      WORDLE_GOOGLE_CLIENT_ID: "${WORDLE_GOOGLE_CLIENT_ID}"
      WORDLE_GOOGLE_CLIENT_SECRET: "${WORDLE_GOOGLE_CLIENT_SECRET}"
      WORDLE_JWT_SECRET: "${WORDLE_JWT_SECRET}"
      SPRING_DATA_REDIS_HOST: "wordle-duel-service-redis"
      SPRING_DATA_REDIS_PORT: "6379"
    labels:
      - app=wordle-duel-service
      - metrics_scrape=true
      - metrics_path=/actuator/prometheus
      - metrics_port=8088

  wordle-duel-service-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    networks: [ wordle_duel_service_internal ]
    volumes:
      - wordle_duel_service_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 10
    labels:
      - app=wordle-duel-service-redis

  wordle-duel:
    image: dariomr8/wordle-duel:latest
    restart: unless-stopped
    expose:
      - "80"
    networks: [ backend ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 5s
      retries: 3
